### ISSUE TITLE
Formato reporte

### ISSUE THREAD

**Issue by DrJoseGallardo** [RFOS33/Ricardo-Oyarzun-Salazar#1]
Estimado Ricardo:

No olvidar que el reporte debe tener esta estructura.

Planteamiento del problema a resolver (4 puntos).
Descripción detallada de los datos originales (4 puntos).
Análisis exploratorio de datos (4 puntos).
Análisis estadístico de los datos (4 puntos).
Interpretación de resultados y conclusión (4 puntos).

Saludos

**Comment by RFOS33** [comment]
Estimado profesor, muchas gracias por el recordatorio.
Saludos cordiales
