### ISSUE TITLE
Sobre métodos estadísticos

### ISSUE THREAD

**Issue by MARCPUCV** [RFOS33/Ricardo-Oyarzun-Salazar#2]
Muy buenas tardes estimado Ricardo, 

Tengo la siguiente consulta, veo en el Readme de su proyecto que va a realizar un ANOVA, va a ser desde el enfoque de los métodos no paramétricos?, o solo va a probar los supuestos con el enfoque no paramétrico usando la librería WRS2?

Saludos!!

**Comment by RFOS33** [comment]
Estimada profesora el paquete WRS2 es para realizar el ANOVA que funciona cuando existe heterocedasticidad, sin embargo no me ha funcionado bien. Me gustaría poder evaluar varios método para determinar cual es el mejor, había pensado en un modelo lineal mixto colocando el tiempo como variable mixta, y así realizar la comparación con el ANOVA con heterocedasticdad.
Saludos

**Comment by MARCPUCV** [comment]
Muy buenos días estimado Ricardo,
La variable tiempo como la estás manejando, como criterio de clasificación o como covariable? si lo tomas como criterio de clasificación cuántos niveles tendría? Estaré atenta.
Saludos!!

**Comment by RFOS33** [comment]
La variable tiempo la estoy manejando como una fuente de variación principal y es un factor con 18 a 15 niveles dependiendo de la variable respuesta.
Saludos
